### ISSUE TITLE
Zoom support

### ISSUE THREAD

**Issue by AlexJitianu** [oxygenxml/TEI-Facsimile-Plugin#2]
Add support for zooming the image. It would make it easier to mark certain areas.

**Comment by lb42** [comment]
Yes. Very necessary, since scaling info provided on <tei:graphic> is always ignored.

**Comment by AlexJitianu** [comment]
You can now zoom an image. There are button on the toolbar and you can also use CTRL+mouse scroll. 
I'm not sure if I should do anything more about the " scaling info provided on tei:graphic"... Lou, if you think it's also something good to have perhaps you can add a new issue with a more detailed description.
