### ISSUE TITLE
Add a way of aligning zones with existing transcribed text elements

### ISSUE THREAD

**Issue by lb42** [oxygenxml/TEI-Facsimile-Plugin#3]
If you have an existing transcription inside a &lt;text> element, it would be useful to be able to select an element of it and associate it with the corresponding &lt;zone> e.g. using xml:id on the &lt;zone> and @facs on the element.

**Comment by AlexJitianu** [comment]
I've added a **Copy/Generate ID** action in the contextual menu presented for an area (in the image view). What this action does is:
1. if the zone doesn't have an ID it will generate one. The pattern is read from **etc/id_pattern.txt** and it accepts Oxygen editor variables.
2. copy *#id* to clipboard

After invoking this action you will go on an element from <text> and just paste the value inside an @facs. I hope is enough... if not, I'm open to suggestions :)
