### ISSUE TITLE
Modifying a zone loses link to image

### ISSUE THREAD

**Issue by lb42** [oxygenxml/TEI-Facsimile-Plugin#4]
If you change an existing &lt;zone; in the document, e.g. altering its @ulx value, selecting the element no longer displays a red bounding box on the image. This happens even if you reload the document.

**Comment by AlexJitianu** [comment]
Currently the view doesn't react to changes in the editor area so in situations like the one you described they will not be synchronized anymore. The solution is to reload the image.

I think the solution to such problem is for the view to listen to document changes and automatically update the affected zones/rectangles (or add any new zones for that matter).

**Comment by AlexJitianu** [comment]
The view and the editor are now synchronized (#5) so I think the issue reported here is also solved.
