### ISSUE TITLE
Zones on images larger than the screen size and bounding box not drawing on reload

### ISSUE THREAD

**Issue by MedievalMatt** [oxygenxml/TEI-Facsimile-Plugin#7]
Hello,

There are two issues I've run into in trying out the plugin:

1. I have large image files as I plan to allow people to zoom in to look at details.  Because of this I cannot create a bounding box around my zone that fits the file.  What I've done as a workaround is used the plugin to draw two boxes, then used the ulx and uly from the first and the lrx and lry from the second to set the limits of my bounding area.

2. When I create a bounding box using the tool or manually and reload the file the bounding box disappears and I'm left with what appears to be just the image.  My understanding from looking at README.md is that the bounding box should appear so long as no manual changes are made in that session.

The file I'm using (which uses the alternate sourceDoc/surfaceGrp/surface setup rather than text/body|facsimile/surface) can be found at http://matthewedavis.net/tei/Clopton_Testament.xml and the image is attached to this note.
![sw_test_1](https://cloud.githubusercontent.com/assets/5084295/5813757/cf678cf6-a050-11e4-9af0-fbaf0b95a3f8.jpg)

**Comment by MedievalMatt** [comment]
Also, thinking about it would it be possible to use the points system with the plugin as well as a future implementation item?  I don't always have boxes I need to bound within.

**Comment by AlexJitianu** [comment]
There is an issue already recorded (https://github.com/oxygenxml/TEI-Facsimile-Plugin/issues/1). I'll add your vote for it.

**Comment by AlexJitianu** [comment]
I think the issues reported here have been solved by these new features:
- zoom support (actions on the toolbar or CTRL+mouse scroll). If a image is too large you can zoom out and draw the rectangle.
- area resize. You can drag an already existing rectangle by a corner and resize it.
- editor-view synchronization. A new area added in the view will automatically be added in the editor. Likewise,  if the editor is changed the view will automatically reload the areas.

For the points system there is an issue already recorded (#1)
